export default {
    MAS_GRANT_FLOW_PASSWORD: 2,
    MAS_GRANT_FLOW_CLIENT_CREDENTIALS: 1,
    MAS_USER: 1,
    MAS_APPLICATION: 2,
    MAS_STATE_NOT_CONFIGURED: 1,
    MAS_STATE_NOT_INITIALIZED: 2,
    MAS_STATE_STARTED: 3,
    MAS_STATE_STOPPED: 4
};
